### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by jeffryhartanto** [lohanitech/ion-electron#1]
Hi, I clone the code and run `npm install`. But when I type `ionic serve` I got below runtime error. How can I fix this issue? BTW, I appreciate your blog post, awesome.

```
Runtime Error
require is not defined
Stack
ReferenceError: require is not defined
    at Object.defineProperty.value (http://localhost:8100/build/main.js:114252:1)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:57312:67)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:57229:78)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:57271:69)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:104567:75)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:78191:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:114261:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
```

**Comment by lohanidamodar** [comment]
Thank you for liking my blog post.

If you are trying to serve and view it on browser it won't work,
After adding the electron related functions, it will only work with electron.

run `ionic serve` in one terminal run `npm run electron test` in another terminal.

**Comment by jeffryhartanto** [comment]
Running `npm run electron test` will only open a blank program. To be precise, the problem occurs when I finish implementing the part 2 of the tutorial. Any idea how to fix this? Because I want to create an app that can be ran in multiple platforms.

**Comment by jeffryhartanto** [comment]
`After adding the electron related functions, it will only work with electron.`

Does that mean I cannot build cross platform app if I need to use electron related functions? So, what is the purpose of part 2 of the tutorial? Is it to show that you can use ionic in electron but not vice versa?

**Comment by lohanidamodar** [comment]
Yes, for now you can use cross platform for desktop (Mac, Windows and Linux) using electron. But if you need desktop as well as mobile platform you need to make two copies for now, but I heard they will soon build official support for electron as well. For now I have not been able to devise or find other better solution.

**Comment by jeffryhartanto** [comment]
Ohhh.. But still your blog post kinda helps for developing cross-platform app, as long as we don't need to use electron functions.. Awesome..
BTW, maybe you can look at Meteor.js, however as I know it can only support MongoDB for now.

Closing this issue..
