### ISSUE TITLE
Can I apply Angular coding style with Electron API in Ionic?

### ISSUE THREAD

**Issue by comseong** [lohanitech/ion-electron#6]
At first, thank you for your answers for previous issues. 
I changed codes in part 2 tutorial by Angular coding style like below because all type definitions for TypeScript is provided by @ types/electron installed. But Electron spits out error like the attachment. Is there any trick to let Electron understand Angular coding style? 

Environment: Electron 1.7.9 and Type definitions for Electron 1.7.9

![image](https://user-images.githubusercontent.com/3951319/32391724-f5be1fd8-c0f4-11e7-9ee1-ac7dcde9190e.png)

Error in Electron:
compiler.es5.js:1694 Uncaught Error: Can't resolve all parameters for ElecZoomProvider: (?).
    at syntaxError (file:///Users/quick-start/www/build/vendor.js:80079:34)
    at CompileMetadataResolver._getDependenciesMetadata (file:///Users/www/build/vendor.js:94315:35)
    at CompileMetadataResolver._getTypeMetadata (file:///Users/www/build/vendor.js:94183:26)
    at CompileMetadataResolver._getInjectableMetadata (file:///Users/www/build/vendor.js:94169:21)
    at CompileMetadataResolver.getProviderMetadata (file:///Users/www/build/vendor.js:94460:40)
    at file:///Users/www/build/vendor.js:94389:49
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (file:///Users/www/build/vendor.js:94349:19)
    at CompileMetadataResolver.getNgModuleMetadata (file:///Users/www/build/vendor.js:94004:50)
    at JitCompiler._loadModules (file:///Users/www/build/vendor.js:105350:70)

**Comment by lohanidamodar** [comment]
This is not possible because as of now, electron does not export individual modules, it exports all apis as single module. hence import * as electron from 'electron'. In order to use the syntax as you used, you need to make custom module yourself. Which is beyond the scope of this tutorial.
